name: Sync GitHub to Hugging Face Hub

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Hub
        uses: huggingface/hub-sync@v0.3.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: siallenga/tourism-purchase-predictor   # replace with your actual HF Space name
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          space_sdk: streamlit
